#nullable disable
using System;
using Rhino.Geometry;

namespace Frahan.Core.Quarry;

// =============================================================================
// BenchBoundary — Phase G of the UX architecture report §7.8 mesh-bench
// rollout. Wraps a Box (always axis-aligned AABB) with an optional Mesh
// (the actual non-rectangular bench geometry).
//
// Design choice: composition over invasive edits. The 11 BCO components
// audited in Appendix C (BCOSolve, BCOOmni, BCOExtract, BCOPareto,
// BCORobust, BCOWatershed, HeteroExt, BCOMixedPack, BCOMixedPack3D,
// BCOAmrr, VtuOut) keep their existing Box inputs. Users wire:
//
//   BenchFromMesh(mesh) → Box → existing BCO component
//   existing BCO Box[] output → ClipBoxesByMesh(mesh) → filtered Box[]
//
// This preserves GUIDs (AGENTS.md §8), keeps the existing 700+ tests
// passing, and lets users opt into mesh-aware workflows without touching
// the 11 production components.
//
// Pure managed.
// =============================================================================

public sealed class BenchBoundary
{
    private BenchBoundary(Box aabb, Mesh mesh)
    {
        Aabb = aabb;
        Mesh = mesh;
    }

    /// <summary>Axis-aligned bounding box of the bench. Always set —
    /// even when constructed from a Mesh, the AABB is derived for use
    /// with Box-based BCO components.</summary>
    public Box Aabb { get; }

    /// <summary>Optional Mesh holding the actual non-rectangular bench
    /// geometry. null if the bench is just a Box. When set, the
    /// <see cref="ContainsBoxCentre"/> helper can be used to filter
    /// candidate boxes generated by BCO components.</summary>
    public Mesh Mesh { get; }

    /// <summary>True iff a Mesh boundary is present (i.e. the user
    /// cared about non-rectangular shape).</summary>
    public bool HasMesh => Mesh != null;

    /// <summary>Construct from a Box. AABB = Box; no Mesh.</summary>
    public static BenchBoundary FromBox(Box aabb) => new BenchBoundary(aabb, null);

    /// <summary>Construct from a Mesh. AABB is derived; Mesh is kept
    /// for the half-space clip.</summary>
    public static BenchBoundary FromMesh(Mesh mesh)
    {
        if (mesh == null) throw new ArgumentNullException(nameof(mesh));
        if (!mesh.IsValid)
            throw new ArgumentException("mesh must be valid.", nameof(mesh));
        var bbox = mesh.GetBoundingBox(true);
        if (!bbox.IsValid)
            throw new ArgumentException("mesh has no valid bounding box.", nameof(mesh));
        var box = new Box(bbox);
        return new BenchBoundary(box, mesh);
    }

    /// <summary>Construct from both: explicit Box AABB plus a Mesh.
    /// Useful when the user wants to keep the original Box for legacy
    /// chains but still expose the Mesh for clipping.</summary>
    public static BenchBoundary FromBoxAndMesh(Box aabb, Mesh mesh)
    {
        if (mesh == null) return FromBox(aabb);
        return new BenchBoundary(aabb, mesh);
    }

    /// <summary>
    /// True if the given Box's centre lies inside this boundary. When
    /// no Mesh is set, the check is against the AABB (always true for
    /// any cell entirely inside the AABB). When a Mesh is set, the
    /// check uses <see cref="Mesh.IsPointInside"/> with the supplied
    /// tolerance.
    /// </summary>
    public bool ContainsBoxCentre(Box cell, double tolerance = 1e-6)
    {
        var c = cell.Plane.PointAt(
            (cell.X.Min + cell.X.Max) * 0.5,
            (cell.Y.Min + cell.Y.Max) * 0.5,
            (cell.Z.Min + cell.Z.Max) * 0.5);
        if (Mesh == null) return AabbContains(Aabb, c);
        if (!Mesh.IsClosed) return AabbContains(Aabb, c); // open mesh — fall back to AABB
        return Mesh.IsPointInside(c, tolerance, false);
    }

    /// <summary>
    /// Stronger containment: sample N corners of the cell and require
    /// that at least <paramref name="insideFractionThreshold"/> of them
    /// lie inside the boundary. Useful when a centre-only test would
    /// admit cells that hang off the bench edge.
    /// </summary>
    public bool ContainsBox(Box cell, double insideFractionThreshold = 0.5,
        double tolerance = 1e-6)
    {
        if (insideFractionThreshold <= 0.0) return true;
        if (Mesh == null) return AabbContainsBox(Aabb, cell);
        if (!Mesh.IsClosed) return AabbContainsBox(Aabb, cell);

        int insideCount = 0;
        var corners = cell.GetCorners();
        for (int i = 0; i < corners.Length; i++)
            if (Mesh.IsPointInside(corners[i], tolerance, false)) insideCount++;
        double frac = (double)insideCount / corners.Length;
        return frac >= insideFractionThreshold;
    }

    private static bool AabbContains(Box aabb, Point3d p)
    {
        if (!aabb.Plane.RemapToPlaneSpace(p, out Point3d local)) return false;
        return local.X >= aabb.X.Min && local.X <= aabb.X.Max
            && local.Y >= aabb.Y.Min && local.Y <= aabb.Y.Max
            && local.Z >= aabb.Z.Min && local.Z <= aabb.Z.Max;
    }

    private static bool AabbContainsBox(Box outer, Box inner)
    {
        // Test 8 corners; require all inside.
        var corners = inner.GetCorners();
        for (int i = 0; i < corners.Length; i++)
            if (!AabbContains(outer, corners[i])) return false;
        return true;
    }
}
